/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.devkm.view;

import com.devkm.interpreter.CommandParser;
import com.devkm.interpreter.InterpreterContext;
import com.devkm.model.Ingredient;
import com.devkm.model.IngredientFactory;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author KAVEESH
 */
public class CustermizePannel extends javax.swing.JFrame {

    private Map<String, Integer> toppingPrices;
    private String selectedFoodItem;
    private int quantity;

    private IngredientFactory ingredientFactory;
    private InterpreterContext interpreterContext;

    /**
     * Creates new form CustermizePannel
     */
    public CustermizePannel(String selectedFoodItem, int quantity) {
        this.selectedFoodItem = selectedFoodItem;
        this.quantity = quantity;
        this.ingredientFactory = new IngredientFactory();
        this.interpreterContext = CommandParser.buildParser();
        initComponents();
        initializeToppingPrices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        submitCustomizationButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        veggiesComboBox = new javax.swing.JComboBox<>();
        meatItemsComboBox = new javax.swing.JComboBox<>();
        saucesComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        customCommandsComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 168, 185));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        submitCustomizationButton.setBackground(new java.awt.Color(132, 94, 194));
        submitCustomizationButton.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        submitCustomizationButton.setText("Confirm");
        submitCustomizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCustomizationButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 157, 255));
        jButton2.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel1.setText("Add more Toppings...");

        jLabel2.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel2.setText("Veggies");

        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel3.setText("Meat Items");

        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel4.setText("Sauces");

        veggiesComboBox.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        veggiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Lettuce", "Tomato", "Onion", "Pickles", "Mushrooms" }));

        meatItemsComboBox.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        meatItemsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Sausage", "Ham", "Ground Beef", "Grilled Chicken", "Chiken" }));

        saucesComboBox.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        saucesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ketchup", "Mustard", "Mayonnaise", "Barbecue Sauce" }));

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel5.setText("Give a Command");

        customCommandsComboBox.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        customCommandsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "extra cheese", "extra chicken", "extra cheese and chicken" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitCustomizationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saucesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meatItemsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(veggiesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customCommandsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veggiesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meatItemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saucesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customCommandsComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitCustomizationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private void initializeToppingPrices() {
        toppingPrices = new HashMap<>();
        toppingPrices.put("Veggie", 100);
        toppingPrices.put("Meat Items", 300);
        toppingPrices.put("Sauces", 200);
    }

    public int calculateTotalPrice() {
        int totalPrice = 0;

        String selectedVeggie = (String) veggiesComboBox.getSelectedItem();
        String selectedMeatItem = (String) meatItemsComboBox.getSelectedItem();
        String selectedSauce = (String) saucesComboBox.getSelectedItem();

        totalPrice += getToppingPrice(selectedVeggie) * quantity;
        totalPrice += getToppingPrice(selectedMeatItem) * quantity;
        totalPrice += getToppingPrice(selectedSauce) * quantity;

        return totalPrice;
    }

    private int getToppingPrice(String topping) {
        return toppingPrices.getOrDefault(topping, 0);
    }
    private void submitCustomizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCustomizationButtonActionPerformed
        submitCustomization();
    }//GEN-LAST:event_submitCustomizationButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      goBack();
    }//GEN-LAST:event_jButton2ActionPerformed
   private void goBack() {
        // Logic to go back to the previous screen (OrderManagement or CustomizePanel)
        // ...
        // Close the current frame
        OrderManagement om = new OrderManagement();
        om.setVisible(true);
        this.dispose();
    }
    private void submitCustomization() {

        String selectedVeggies = (String) veggiesComboBox.getSelectedItem();
        String selectedMeatItems = (String) meatItemsComboBox.getSelectedItem();
        String selectedSauces = (String) saucesComboBox.getSelectedItem();

        Ingredient veggies = ingredientFactory.getIngredient(selectedVeggies);
        Ingredient meatItems = ingredientFactory.getIngredient(selectedMeatItems);
        Ingredient sauces = ingredientFactory.getIngredient(selectedSauces);

        // Example: Customize the ingredients
        interpreterContext.interpret(veggies, (String) customCommandsComboBox.getSelectedItem());
        interpreterContext.interpret(meatItems, (String) customCommandsComboBox.getSelectedItem());
        interpreterContext.interpret(sauces, (String) customCommandsComboBox.getSelectedItem());

        // Print the customization details
        System.out.println("\nCustomization Details:");
        System.out.println("Selected Food Item: " + selectedFoodItem);
        System.out.println("Selected Toppings: ");
        System.out.println("  Veggies - " + veggies.getName());
        System.out.println("  Meat Items - " + meatItems.getName());
        System.out.println("  Sauces - " + sauces.getName());
        System.out.println("Selected Custom Command: " + customCommandsComboBox.getSelectedItem());

        ProcessPanel processPanel = new ProcessPanel();
        processPanel.setVisible(true);
        this.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustermizePannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustermizePannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustermizePannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustermizePannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> customCommandsComboBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JComboBox<String> meatItemsComboBox;
    private javax.swing.JComboBox<String> saucesComboBox;
    private javax.swing.JButton submitCustomizationButton;
    private javax.swing.JComboBox<String> veggiesComboBox;
    // End of variables declaration//GEN-END:variables
}
