package com.devkm.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.devkm.view.ProcessPanel;
import com.devkm.view.CustermizePannel;


public class OrderManagement extends javax.swing.JFrame {

    /**
     * Creates new form OrderManagement
     */
    public OrderManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customizeOrderButton = new javax.swing.JButton();
        submitOrderButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        foodComboBox = new javax.swing.JComboBox<>();
        quantityTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        orderStatusComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chatBoxButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Management");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(75, 68, 83));
        Left.setForeground(new java.awt.Color(204, 204, 255));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setBackground(new java.awt.Color(75, 68, 83));
        jLabel2.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Syzygy Food Corner");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("www.Syzygy.store");

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Food\\728964_eating_fast food_food_pizza_kitchen_icon.png")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(112, 112, 112)
                .addComponent(jLabel4)
                .addGap(46, 46, 46))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 400, 500);

        Right.setBackground(new java.awt.Color(176, 168, 185));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel1.setText("Manage Your Order");

        customizeOrderButton.setBackground(new java.awt.Color(255, 128, 102));
        customizeOrderButton.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        customizeOrderButton.setText("Customerize Order");
        customizeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizeOrderButtonActionPerformed(evt);
            }
        });

        submitOrderButton.setBackground(new java.awt.Color(132, 94, 194));
        submitOrderButton.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        submitOrderButton.setText("Submit Order");
        submitOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitOrderButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel5.setText("Select Food Item");

        foodComboBox.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        foodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Veggie Pizza", "Chicken Pizza", "Chicken Burger", "Veggie Burger" }));

        quantityTextField.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel6.setText("Enter Quantity");

        orderStatusComboBox.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        orderStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Take Away" }));

        jLabel7.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel7.setText("Order Status");

        chatBoxButton.setBackground(new java.awt.Color(0, 157, 255));
        chatBoxButton.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        chatBoxButton.setText("Chat Box");
        chatBoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBoxButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantityTextField)
                            .addComponent(customizeOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(foodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chatBoxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(68, 68, 68))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(customizeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chatBoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(submitOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel1.add(Right);
        Right.setBounds(400, 0, 450, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customizeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizeOrderButtonActionPerformed
        openCustomizePanel();
    }//GEN-LAST:event_customizeOrderButtonActionPerformed

    private void chatBoxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBoxButtonActionPerformed
        openChatPanel();
    }//GEN-LAST:event_chatBoxButtonActionPerformed

    private void submitOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitOrderButtonActionPerformed
        submitOrder();
    }//GEN-LAST:event_submitOrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private void submitOrder() {
        // Validation logic before redirecting to ProcessPannel.java
        String selectedFood = (String) foodComboBox.getSelectedItem();
        String orderStatus = (String) orderStatusComboBox.getSelectedItem();
        String quantityText = quantityTextField.getText();

        if ("Select".equals(selectedFood)) {
            JOptionPane.showMessageDialog(this, "Please select a Food item.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!isPositiveInteger(quantityText)) {
            JOptionPane.showMessageDialog(this, "Please enter a positive integer for quantity.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            // Proceed to ProcessPannel
            ProcessPanel processPannel = new ProcessPanel();

            processPannel.setVisible(true);
            this.dispose();
            // Additional logic for processing the order...
        }
    }

   private void openCustomizePanel() {
    // Logic to open CustomizePannel.java JFrame
    String selectedFoodItem = (String) foodComboBox.getSelectedItem();
    String quantityText = quantityTextField.getText().trim(); // Trim to remove any leading or trailing spaces

    if (quantityText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a quantity.", "Warning", JOptionPane.WARNING_MESSAGE);
    } else {
        try {
            int quantity = Integer.parseInt(quantityText);
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a positive integer for quantity.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                if ("Select".equals(selectedFoodItem)) {
                    JOptionPane.showMessageDialog(this, "Please select a Food item.", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    CustermizePannel customizePanel = new CustermizePannel(selectedFoodItem, quantity);
                    customizePanel.setVisible(true);
                    this.dispose();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid integer for quantity.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
}


    private void openChatPanel() {
        // Logic to open ChatPannel.java JFrame
        ChatPannel chatPannel = new ChatPannel();
        chatPannel.setVisible(true);
        this.dispose();
    }

    private boolean isPositiveInteger(String text) {
        try {
            int quantity = Integer.parseInt(text);
            return quantity > 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JButton chatBoxButton;
    private javax.swing.JButton customizeOrderButton;
    private javax.swing.JComboBox<String> foodComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> orderStatusComboBox;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton submitOrderButton;
    // End of variables declaration//GEN-END:variables
}
